import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Steam Browser Shortcuts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://imgur.com/ErdAEqi">SteamPin 📌!</a>
        </h1>

        <p className={styles.description}>
          Easy shortcut page for Steam Browser
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="https://google.com/" className={styles.card}>
            <h2>Google &rarr;</h2>
            <p>Just your typical google.</p>
          </a>

          <a href="https://app.destinyitemmanager.com/" className={styles.card}>
            <h2>DIM &rarr;</h2>
            <p>Destiny Item Manager</p>
          </a>

          <a href="https://www.todayindestiny.com/" className={styles.card}>
            <h2>Today-in-destiny &rarr;</h2>
            <p>A summary of what&apos;s available in Destiny today.</p>
          </a>

          <a href="https://d2armorpicker.com/" className={styles.card}>
            <h2>D2ArmorPicker &rarr;</h2>
            <p>A simple armor min-max tool by Mijago.</p>
          </a>
        </div>
        <p>NB: Some of these shortcut need Steam Authentication to use, I&apos;m not responsible if anything happend :&#41;</p>
        {/* <p>Although i personally use these tools 😁</p> */}
      </main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by GhxsT
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
}
